
# Monitor Configurations:
monitorv2 {
    output = DP-1
    mode = 1920x1080@120
    position = 0x0
    scale = 1
}

monitorv2 {
    output = eDP-1
    mode = preferred
    position = 1920x0
    scale = 2
}

monitorv2 {
    output = DP-2
    mode = 1920x1080@120
    position = 0x0
    scale = 1
}

monitorv2 {
    output = eDP-2
    mode = preferred
    position = 1920x0
    scale = 2
}

# General Configurations:
general {
    # Application Margin Rules:
    gaps_in = 5
    gaps_out = 15
}

