
# Monitor Configurations:
monitor = DP-1, 1920x1080@120, 0x0, 1
monitor = eDP-1, preferred, 1920x0, 2

# General Configurations:
general {
    # Application Margin Rules:
    gaps_in = 5
    gaps_out = 15
}

